-- This module serves as the root of the `PhysicsOfConsciousness` library.
-- Import modules here that should be built as part of the library.
import PhysicsOfConsciousness.Phase1_Primitives
import PhysicsOfConsciousness.Phase2_SimplicialBridge
import PhysicsOfConsciousness.Phase3_CombinatorialThermodynamics
import PhysicsOfConsciousness.Phase3_KLBound
import PhysicsOfConsciousness.Phase3_MeasureThermodynamics
import PhysicsOfConsciousness.Phase4_KuramotoDynamics
import PhysicsOfConsciousness.Axioms
import PhysicsOfConsciousness.Phase4_MacroscopicScaling
import PhysicsOfConsciousness.Phase5_GlobalSection
import PhysicsOfConsciousness.Phase6_ReflexiveTopology
import PhysicsOfConsciousness.Phase7_HardwareComparison
import PhysicsOfConsciousness.Phase8_ContinuousField
import PhysicsOfConsciousness.Examples
