#!/usr/bin/env bash
# Deterministic rendering from saved data. Does not invoke Lean or simulations.
set -euo pipefail
cd "$(dirname "$0")/.."
selection=${1:-proof_companion/selection.json}
data_dir=${2:-proof_companion/data}
output_dir=${3:-proof_companion/generated}
mkdir -p "$output_dir"

jq -e '
  length > 0 and
  ([.[].id] | length == (unique | length)) and
  ([.[].declarations[].id] | length == (unique | length)) and
  ([.[].declarations[].name] | length == (unique | length)) and
  all(.[]; (.id | test("^[a-z0-9-]+$")) and
    (.source | test("^[A-Za-z0-9_/]+[.]lean$")) and
    all(.declarations[]; (.id | test("^[a-z0-9-]+$"))))
' "$selection" >/dev/null

printf '%% Generated by proof_companion/render.sh from saved JSON; do not edit.\n' \
  >"$output_dir/declarations.tex"
printf 'id\tdeclaration\tsource\tline\ttactic_records\n' >"$output_dir/coverage.tsv"
while IFS=$'\t' read -r module_id source; do
  snapshot="$data_dir/$module_id.json"
  # One jq pass per module. Reading a multi-megabyte snapshot once per selected
  # declaration is what stopped this scaling past the twelve-result pilot; the
  # text is carried out base64-encoded so that statements containing tabs or
  # newlines survive the shell.
  wanted=$(jq -c --arg id "$module_id" '[.[] | select(.id == $id) | .declarations[]]' \
    "$selection")
  jq -r --arg source "$source" --argjson wanted "$wanted" '
    if .schema_version != 1 or .source_file != $source then
      error("snapshot does not match the selected source: \($source)")
    else . end
    | . as $snap
    | $wanted[]
    | . as $want
    | ([$snap.declarations[] | select(.name == $want.name)]) as $found
    | if ($found | length) != 1 then
        error("expected exactly one record for \($want.name), found \($found | length)")
      else $found[0] end
    | [ $want.id
      , $want.name
      , (.start.line | tostring)
      , (.tactics | length | tostring)
      , ((.statement + "\n") | @base64)
      , ( [.proof_dependencies[] | select(startswith("PhysicsOfConsciousness."))]
          | if length == 0 then "" else (join("\n") + "\n") end | @base64 )
      ] | @tsv
  ' "$snapshot" |
  while IFS=$'\t' read -r id name line count statement_b64 deps_b64; do
    printf '%s' "$statement_b64" | base64 -d >"$output_dir/$id.statement.txt"
    printf '%s' "$deps_b64" | base64 -d >"$output_dir/$id.dependencies.txt"
    printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$name" "$source" "$line" "$count" \
      >>"$output_dir/coverage.tsv"
    {
      printf '\\subsection{%s}\\label{decl:%s}\n' "$id" "$id"
      printf '\\noindent\\nolinkurl{%s}\\par\n' "$name"
      printf '\\noindent\\href{../%s}{Source, line %s}; %s nested tactic records.\\par\n' \
        "$source" "$line" "$count"
      printf '\\VerbatimInput{generated/%s.statement.txt}\n' "$id"
      if test -s "$output_dir/$id.dependencies.txt"; then
        printf '\\noindent Direct project constants in the proof term:\n'
        printf '\\VerbatimInput{generated/%s.dependencies.txt}\n' "$id"
      fi
    } >>"$output_dir/declarations.tex"
  done
done < <(jq -r '.[] | [.id, .source] | @tsv' "$selection")

{
  printf '%% Generated by proof_companion/render.sh; do not edit.\n'
  printf '\\newcommand{\\CompanionTheoremCount}{%s}\n' \
    "$(jq '[.[].declarations[]] | length' "$selection")"
  printf '\\newcommand{\\CompanionModuleCount}{%s}\n' "$(jq 'length' "$selection")"
  printf '\\newcommand{\\CompanionTacticRecordCount}{%s}\n' \
    "$(awk -F '\t' 'NR > 1 { total += $5 } END { print total + 0 }' "$output_dir/coverage.tsv")"
} >"$output_dir/metadata.tex"

# A small, real trace is useful on paper; the full nested trees stay in JSON.
jq -r '.declarations[] | select(.name | endswith("richDensity_not_const")) |
  .tactics | map(select(.source == "intro h" or
    .source == "have hl := congrFun h Site.left" or .source == "simp [richDensity] at hl")) |
  unique_by([.start.line, .start.column, .source]) | sort_by(.start.line, .start.column) |
  .[] | "SOURCE LINE \(.start.line): \(.source)\nBEFORE\n" +
    (.goals_before | join("\n\n")) + "\nAFTER\n" +
    (if (.goals_after | length) == 0 then "No goals remain." else
      (.goals_after | join("\n\n")) end) + "\n"' \
  "$data_dir/witness.json" >"$output_dir/witness-trace.txt"
test -s "$output_dir/witness-trace.txt"
jq -r '.structures[] | .fields[] |
  select(.name | endswith("section_agrees_of_phase_eq") or
    endswith("thermodynamic_equilibrium")) |
  .name + "\n" + .statement + "\n"' \
  "$data_dir/gluing.json" >"$output_dir/physical-fields.txt"
test -s "$output_dir/physical-fields.txt"
