#!/usr/bin/env python3
"""
Fermi estimate: K > D from published numbers.

K = N * Δt * f
  N    = number of neurons within one LFP decay length
  Δt   = ephaptic phase shift per neuron (seconds)
  f    = oscillation frequency (Hz)
  D    = Lorentzian half-width of intrinsic frequency spread (rad/s)

Usage:
  python simulations/fermi_estimate_check.py                        # default values
  python simulations/fermi_estimate_check.py -v                      # verbose per-step
  python simulations/fermi_estimate_check.py E=5 lam=0.3            # override params
  python simulations/fermi_estimate_check.py --write-tex             # regenerate fermi_params.tex

References:
  Anastassiou et al. 2011, Nat Neurosci 14:217-223
  Anastassiou & Koch 2015, Curr Opin Neurobiol 31:95-103
  Lindén et al. 2011, Neuron 72:859-872
  Herculano-Houzel 2009, Front Hum Neurosci 3:31
  Buzsáki & Draguhn 2004, Science 304:1927-1929
  Strogatz & Mirollo 1991, J Stat Phys 63:613-635
"""

import argparse
import math
import sys
from pathlib import Path
from typing import Any

# ── default parameters ──────────────────────────────────────────────────
DEFAULTS = {
    "E": 3.0,  # endogenous field (mV/mm)
    "shift": 0.4,  # ephaptic shift per mV/mm (ms)
    "lam": 0.2,  # LFP decay length (mm)
    "rho": 5e4,  # neuron density (mm^-3)
    "f": 40.0,  # oscillation frequency (Hz)
    "D": 1.5,  # Lorentzian half-width (rad/s)
    "Kc_factor": 2.0,  # K_c = Kc_factor * D
}

# Measured field range (mV/mm) across all EEG bands
FERMI_FIELD_MIN = 1
FERMI_FIELD_MAX = 5

# Measured decay-length range (mm)
FERMI_LAM_MIN = 0.1
FERMI_LAM_MAX = 0.3

# Band-specific parameters: (field_mVmm, freq_Hz)
BANDS = {
    "gamma": (0.5, 40),
    "beta": (1.0, 20),
    "alpha": (1.5, 10),
    "theta": (3.0, 6),
    "delta": (2.0, 2),
}

# Conservative bound (low end of every published range)
CONS_E = 1.0
CONS_SHIFT = 0.3
CONS_LAM = 0.15
CONS_D = 2.0


# One evaluated parameter set: the inputs, the intermediate counts and the
# ratio.  Heterogeneous by nature (the name is a string), hence `Any`.
Scenario = dict[str, Any]


def compute_k(
    E: float, shift: float, lam: float, rho: float, f: float
) -> tuple[float, float, float]:
    """Return (N, dt_n, K) where K = N * dt_n * f."""
    vol = 4.0 / 3.0 * math.pi * lam**3
    N = rho * vol
    dt_n = E * shift
    K = N * (dt_n / 1000.0) * f
    return N, dt_n, K


def scenario(
    name: str, E: float, shift: float, lam: float, rho: float, f: float, D: float
) -> Scenario:
    """Evaluate one scenario and return a result dict."""
    N, dt_n, K = compute_k(E, shift, lam, rho, f)
    Kc = DEFAULTS["Kc_factor"] * D
    ratio = K / D
    return {
        "name": name,
        "E": E,
        "shift": shift,
        "lam": lam,
        "rho": rho,
        "f": f,
        "D": D,
        "N": N,
        "dt_n": dt_n,
        "K": K,
        "Kc": Kc,
        "ratio": ratio,
    }


def format_result(r: Scenario, verbose: bool = False) -> str:
    """Format a result dict as a string."""
    lines = [
        f"  E = {r['E']:.1f} mV/mm,  shift = {r['shift']:.2f} ms/(mV/mm),  "
        f"lambda = {r['lam']:.2f} mm",
        f"  rho = {r['rho']:.1e} mm^-3,  f = {r['f']:.0f} Hz,  D = {r['D']:.1f} rad/s",
        f"  N(neurons within lambda) = {r['N']:.0f},  dt_n = {r['dt_n']:.2f} ms",
        f"  K = {r['K']:.1f},  K_c = {r['Kc']:.1f},  K/D = {r['ratio']:.1f}",
    ]
    if verbose:
        vol = 4.0 / 3.0 * math.pi * r["lam"] ** 3
        lines.insert(1, f"  volume = {vol:.4f} mm^3")
    return "\n".join(lines)


# ── Tex generation: single source of truth ──────────────────────────────


TEX_HEADER = """%% Auto-generated by simulations/fermi_estimate_check.py --write-tex
%% Do not edit manually. Edit the Python script instead and regenerate.
%% Frequency-band field values from Anastassiou & Koch 2011, 2015.

% --- Global parameters ---"""


def _tc(name: str, val: object, comment: str = "") -> str:
    return f"\\newcommand{{\\{name}}}{{{val}}}           % {comment}"


def _tce(name: str, args: str, expr: str) -> str:
    """Command with args whose value is an \\fpeval expression."""
    params = f"[{args}]" if args else ""
    return f"\\newcommand{{\\{name}}}{params}{{\\fpeval{{{expr}}}}}"


def write_tex(path: str) -> None:
    """Write fermi_params.tex from this script's constants."""
    D_val = DEFAULTS["D"]
    lam = DEFAULTS["lam"]
    shift = DEFAULTS["shift"]

    def n_expr(lam_sym: str = "\\fermiLam") -> str:
        return f"round(4/3*pi*{lam_sym}^3*{DEFAULTS['rho']:.0e},0)"

    def k_expr(e: str = "#1", f: str = "#2", lam_sym: str = "\\fermiLam") -> str:
        return f"round(4/3*pi*{lam_sym}^3*{DEFAULTS['rho']:.0e} * ({e}*{shift}/1000) * {f}, 0)"

    def kd_expr(
        e: str = "#1", f: str = "#2", lam_sym: str = "\\fermiLam", D_sym: str = "\\fermiD"
    ) -> str:
        return (
            f"round(4/3*pi*{lam_sym}^3*{DEFAULTS['rho']:.0e}"
            f" * ({e}*{shift}/1000) * {f} / {D_sym}, 1)"
        )

    lines = [
        TEX_HEADER,
        "",
        _tc("fermiLam", lam, "LFP decay length (mm)"),
        _tc("fermiLamMin", FERMI_LAM_MIN, "measured lower bound"),
        _tc("fermiLamMax", FERMI_LAM_MAX, "measured upper bound"),
        _tc("fermiRho", f"{DEFAULTS['rho']:.0e}", "neuron density (mm$^{-3}$)"),
        _tc("fermiShift", shift, "ephaptic shift per mV/mm (ms)"),
        _tc("fermiD", D_val, "Lorentzian half-width (rad/s)"),
        _tc("fermiThreshold", DEFAULTS["Kc_factor"], "$K_c/D$ (universal constant)"),
        "",
        "% --- Measured field range (mV/mm) across all EEG bands ---",
        _tc("fermiFieldMin", FERMI_FIELD_MIN, ""),
        _tc("fermiFieldMax", FERMI_FIELD_MAX, ""),
        "",
        "% --- Band-specific field amplitudes (mV/mm) and frequencies (Hz) ---",
    ]

    for band, (e_val, f_val) in BANDS.items():
        lines.append(f"\\newcommand{{\\fermiE{band}}}{{{e_val}}}")
        lines.append(f"\\newcommand{{\\fermiF{band}}}{{{f_val}}}")

    lines += [
        "",
        "% --- Conservative bound parameters (low end of every range) ---",
        _tc("fermiConsE", CONS_E, "conservative field (mV/mm)"),
        _tc("fermiConsShift", CONS_SHIFT, "conservative shift per mV/mm (ms)"),
        _tc("fermiConsLam", CONS_LAM, "conservative decay length (mm)"),
        _tc("fermiConsD", CONS_D, "conservative Lorentzian width (rad/s)"),
        "",
        r"%% --- Parameterized kernel functions ---",
        r"%% \fermiK{E}{f} = coupling constant K, e.g. \fermiK{\fermiEtheta}{\fermiFgamma}",
        r"%% \fermiKD{E}{f} = ratio K/D",
        r"%% \fermiKDlam{E}{f}{lam} = K/D with explicit lam (for range statement)",
        "",
        _tce("fermiN", "", n_expr()),
        _tce("fermiK", "2", k_expr()),
        _tce("fermiKD", "2", kd_expr()),
        _tce("fermiKDlam", "3", kd_expr(lam_sym="#3")),
        "",
        "% --- Pre-computed values used directly in prose ---",
        _tce("fermiPhAdv", "", f"round({BANDS['theta'][0]}*{shift}/1000*{BANDS['theta'][1]},3)"),
        _tce(
            "fermiKDcons",
            "",
            kd_expr(str(CONS_E), str(BANDS["gamma"][1]), "\\fermiConsLam", "\\fermiConsD"),
        ),
    ]

    Path(path).write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}")


# ── CLI ─────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Fermi estimate: does K exceed D for cortical parameters?"
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="show per-step arithmetic")
    parser.add_argument(
        "--write-tex",
        metavar="PATH",
        nargs="?",
        const="simulations/fermi_params.tex",
        help="regenerate fermi_params.tex from this script's constants",
    )
    parser.add_argument("overrides", nargs="*", help="PARAM=value overrides, e.g. E=5 lam=0.3")
    return parser


def _apply_overrides(overrides: list[str]) -> dict[str, float]:
    """DEFAULTS with any well-formed PARAM=value overrides applied.

    A malformed or unknown override is reported and skipped rather than
    aborting the run: the script is a calculator, and printing the estimate
    from the parameters it did understand is more useful than refusing.
    """
    params = dict(DEFAULTS)
    for ov in overrides:
        if "=" not in ov:
            print(f"ignoring malformed override: {ov}")
            continue
        key, val = ov.split("=", 1)
        if key not in params:
            print(f"unknown parameter: {key} (valid: {', '.join(sorted(params.keys()))})")
            continue
        try:
            params[key] = float(val)
        except ValueError:
            print(f"invalid number for {key}: {val}")
    return params


def _build_scenarios(params: dict[str, float]) -> list[Scenario]:
    """The default parameter set plus the four bracketing cases."""
    return [
        scenario("Lower bound", 1.5, 0.3, 0.15, 5e4, params["f"], params["D"]),
        scenario(
            "Default (mid-range)",
            params["E"],
            params["shift"],
            params["lam"],
            params["rho"],
            params["f"],
            params["D"],
        ),
        scenario("Upper bound", 5.0, 0.5, 0.3, 8e4, params["f"], params["D"]),
        scenario("Gamma-band", 0.5, 0.4, 0.2, 5e4, 40.0, params["D"]),
        scenario("Theta-band", 3.0, 0.4, 0.2, 5e4, 6.0, params["D"]),
    ]


def _print_scenarios(scenarios: list[Scenario], verbose: bool) -> None:
    print("=" * 64)
    print("  Fermi Estimate: K > D for endogenous cortical fields")
    print("=" * 64)
    print()

    for s in scenarios:
        print(f">>> {s['name']}")
        print(format_result(s, verbose=verbose))
        print()

    print("── Summary ─────────────────────────────────────────────────────")
    print(f"{'Scenario':<30s} {'N':>8s} {'K':>8s} {'K/D':>8s}  {'Pass?':>6s}")
    print("-" * 64)
    for s in scenarios:
        ok = "YES" if s["ratio"] > s["Kc"] / s["D"] else "NO"
        print(f"{s['name']:<30s} {s['N']:>8.0f} {s['K']:>8.1f} {s['ratio']:>8.1f}  {ok:>6s}")
    print()


def _print_sensitivity(params: dict[str, float]) -> None:
    worst = scenario("Conservative bound", CONS_E, CONS_SHIFT, CONS_LAM, 5e4, params["f"], CONS_D)
    print(
        f"Conservative bound:  K/D = {worst['ratio']:.1f},"
        f"  threshold = {worst['Kc'] / worst['D']:.1f}"
    )
    print()

    print("── Sensitivity to D (default params, D varied) ─────────────────")
    for D_val in [0.5, 1.0, 1.5, 2.0, 3.0, 5.0]:
        sen = scenario(
            "", params["E"], params["shift"], params["lam"], params["rho"], params["f"], D_val
        )
        ok = sen["ratio"] > sen["Kc"] / sen["D"]
        print(f"  D = {D_val:3.1f} rad/s  =>  K/D = {sen['ratio']:>8.1f}  {ok}")
    print()


def _check_margin(scenarios: list[Scenario]) -> None:
    """Exit non-zero if any physiological scenario falls below `K_c/D = 2`."""
    print("── Checking the magnitude gap ──────────────────────────────────")
    min_ratio = min(s["ratio"] for s in scenarios)
    print(f"  Min K/D across physiological scenarios: {min_ratio:.1f}")
    print(f"  Survival margin (ratio / 2): {min_ratio / 2:.1f}x")
    print()

    if min_ratio < 2:
        print("  WARNING: some scenarios fall below threshold!")
        sys.exit(1)
    print("  All scenarios comfortably clear threshold.")


def main() -> None:
    args = _build_parser().parse_args()
    params = _apply_overrides(args.overrides)

    if args.write_tex:
        write_tex(args.write_tex)
        return

    scenarios = _build_scenarios(params)
    _print_scenarios(scenarios, args.verbose)
    _print_sensitivity(params)
    _check_margin(scenarios)


if __name__ == "__main__":
    main()
