"""Regenerate F5/F6 reports from compact JSON summaries; no simulation imports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

FIGURES = Path(__file__).resolve().parent / "figures"
Row = dict[str, Any]


def f5_table(records: list[Row]) -> list[str]:
    lines = [
        "| Seed | Rate | Interval | dt | Q3 objective/frozen | Q4 objective/frozen | "
        "Q3 r | Q4 r | Within/between | Blind percentile | Objective / coherence / alignment |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in records:
        flags = " / ".join(
            "pass" if row[key] else "fail"
            for key in ("objective_pass", "coherence_pass", "alignment_pass")
        )
        lines.append(
            f"| {row['seed']} | {row['learning_rate']:g} | {row['update_interval']:g} | "
            f"{row['dt']:g} | {row['quarter_objective_ratios'][0]:.6f} | "
            f"{row['quarter_objective_ratios'][1]:.6f} | {row['quarter_order'][0]:.6f} | "
            f"{row['quarter_order'][1]:.6f} | {row['tail_alignment']:.6f} | "
            f"{row['blind_partition_percentile']:.4f} | {flags} |"
        )
    return lines


def f5_report(summary: Row) -> str:
    tuning = summary["tuning"]
    best = min(tuning, key=lambda row: row["worst_objective_ratio"])
    improvements = [100 * (1 - ratio) for ratio in best["quarter_objective_ratios"]]
    eligible = sum(row["objective_pass"] and row["coherence_pass"] for row in tuning)
    lines = [
        "# F5: sustained objective reduction with loss of alignment",
        "",
        "Generated by simulations/followup_report.py from summary.json; do not edit manually.",
        "",
        "Design: tasks/f5_f6_design.md (SHA-256 recorded in the summary).",
        "Squared drift is sum(v**2)/D, not thermodynamic entropy production.",
        "Complete intervals use every integration step on [0,400), excluding the terminal",
        "endpoint. Q3=[200,300), Q4=[300,400). Objective success requires both ratios",
        "<=0.95; coherence requires both mean orders >=0.8. Alignment requires a",
        "second-half within/between ratio <=0.8 and at least 0.1 below frozen, plus",
        "a final blind-partition percentile <=0.05 among 2000 relabellings.",
        "",
        "All tuning outcomes:",
        "",
        *f5_table(tuning),
        "",
        f"Frozen quarter objectives: {tuning[0]['quarter_frozen_objective']}; "
        f"within/between: {tuning[0]['frozen_alignment']:.6f}.",
        "",
        "Immediate post-update readout versus complete-interval time mean:",
        "",
        "| Rate | Interval | Post-update tail objective | Complete second-half objective |",
        "|---:|---:|---:|---:|",
    ]
    for row in tuning:
        lines.append(
            f"| {row['learning_rate']:g} | {row['update_interval']:g} | "
            f"{row['post_update_tail_objective']:.6f} | "
            f"{sum(row['quarter_objective']) / 2:.6f} |"
        )
    lines += [
        "",
        "Post-update diagnostics include t=400, following the original endpoint convention;",
        "the complete-interval estimator excludes it. Kernel alignment is time-weighted",
        "exactly because the kernel is constant between updates.",
        "",
        f"Objective/coherence-eligible tuning cases: {eligible} / {len(tuning)}.",
        f"Selected candidate: {summary['selected_candidate']}. "
        f"Held-out comparisons executed: {len(summary['confirmation'])}.",
        f"Confirmed coexistence: {summary['confirmed']}.",
        "",
        f"The best worst-quarter objective ratio occurs at rate {best['learning_rate']:g},",
        f"interval {best['update_interval']:g}: improvements of {improvements[0]:.3f}% and",
        f"{improvements[1]:.3f}%. This is a smaller reduction than the declared 5% criterion;",
        "it is not evidence of no reduction. It remains a tuning observation, without",
        "held-out or finer-step confirmation. A failed bounded design cannot establish",
        "that no other regime has coexistence, nor validate a sustained-descent headline.",
        "",
        *f5_table(summary["confirmation"]),
        "",
        f"Trajectories: {summary['trajectory_count']}; "
        f"integration and scoring wall time: {summary['runtime_seconds']:.2f} s.",
        "The stop rule forbids expanding the grid or selecting on favorable alignment.",
    ]
    return "\n".join(lines) + "\n"


def f6_report(summary: Row) -> str:
    lines = [
        "# F6: recovery-mechanism discrimination under common observation",
        "",
        "Generated by simulations/followup_report.py from summary.json; do not edit manually.",
        "",
        "Design: tasks/f5_f6_design.md (SHA-256 recorded in the summary).",
        "Observation: exact densities in nine ordered equilibrated windows, with no",
        "individual paths, increments, measurement noise, filtering or finite-sample error.",
        "This is an ideal stationary-observation pilot, not a simulated recovery trajectory.",
        "No independent parameter-measurement protocol is supplied to inference.",
        "",
        "Analytic equivalence: put q(s)=1.5+(b-1.5)s and a=q*r(q). The coupling family",
        "has K=q,D=1; the diffusion family has K=b,D=b/q. Both give concentration a.",
        "The shared-drive family has K=0,D=1 and deterministic restoring drift",
        "-h(s)*sin(theta-psi), with h=a; its stationary density is also exp(a*cos(theta-psi))/Z.",
        "This is an externally prescribed schedule, not oscillator-to-oscillator coupling.",
        "For q<=2 all three densities are uniform. The families differ physically while",
        "their entire stationary distributions, and hence their concentration/order traces, agree.",
        "",
        "Concentration is measured by regression of log density on cosine and sine.",
        "Order is measured independently by circular integration. Each family fits b",
        "in [2.6,4] against concentration; inference receives only densities and window",
        "coordinates. The generating metadata are appended after fitting for evaluation.",
        "",
        "Confusion fractions (row=generator; column=fitted family):",
        "",
        "| Generator | Coupling | Diffusion | Shared drive | Uniquely correct / cases |",
        "|---|---:|---:|---:|---:|",
    ]
    for index, family in enumerate(summary["families"]):
        row = summary["confusion_row_fractions"][index]
        lines.append(
            f"| {family} | {row[0]:.6f} | {row[1]:.6f} | {row[2]:.6f} | "
            f"{summary['uniquely_correct'][index]} / {summary['case_counts'][index]} |"
        )
    lines += [
        "",
        "Every three-way tie is split equally. These fractions are expected allocations",
        "of ties, not observed random classification successes. No case identifies a unique",
        "generator; the declared 80% unique-recovery gate fails for every family.",
        "",
        "Every ideal case (full schedules, measured curves and all fit scores are in the JSON):",
        "",
        "| Generator | True b | psi | Fitted b (coupling / diffusion / drive) | Largest fit SSE |",
        "|---|---:|---:|---|---:|",
    ]
    for case in summary["cases"]:
        fits = [case["fits"][family] for family in summary["families"]]
        fitted = " / ".join(f"{fit['endpoint_ratio']:.7f}" for fit in fits)
        lines.append(
            f"| {case['family']} | {case['endpoint_ratio']:g} | {case['phase']:g} | "
            f"{fitted} | {max(fit['squared_error'] for fit in fits):.3g} |"
        )
    lines += [
        "",
        "Stop: ideal ambiguity, so no noisy/filtered/pooled held-out simulation stage is run.",
        "Adding noise to identical distributions cannot restore identification. These cases",
        "demonstrate an overlap of the declared families, not that all time-dependent",
        "coupling, diffusion and shared-drive models are indistinguishable.",
        "",
        "Additional observation needed: resolved phase increments retain the physical clock.",
        "For an ideal continuous path, quadratic variation has rate 2D; conditional increment",
        "means constrain the drift. Distinguishing endogenous coupling from common forcing",
        "also calls for a measured drive or controlled perturbation. Neither measurement",
        "procedure is validated by this pilot. Independent physical measurements remain",
        "necessary to identify an electromagnetic coupling medium; R4/R5 remain open.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    for name, render in (("plasticity_study", f5_report), ("recovery_mechanisms", f6_report)):
        root = FIGURES / name
        summary = json.loads((root / "summary.json").read_text(encoding="utf-8"))
        (root / "REPORT.md").write_text(render(summary), encoding="utf-8")
        print(f"wrote {root / 'REPORT.md'}")


if __name__ == "__main__":
    main()
