"""Generate G22–G24 publication numerals from compact saved summaries only."""

import json
import math
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parent
FIGURES = ROOT / "figures"
OUTPUT = ROOT / "g_followup_results.tex"


def _read(path: Path) -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(path.read_text()))


def _match(rows: list[dict[str, Any]], key: str, value: str | int) -> dict[str, Any]:
    found = [row for row in rows if row.get(key) == value]
    if len(found) != 1:
        raise ValueError(f"Expected one saved result for {key}={value}")
    return found[0]


def _number(row: dict[str, Any], key: str) -> float:
    value = float(row[key])
    if not math.isfinite(value):
        raise ValueError(f"Nonfinite saved result: {key}")
    return value


def _macro(name: str, value: float) -> str:
    return f"\\newcommand{{\\{name}}}{{{value:.3f}}}"


def render(figures: Path) -> str:
    """Read saved reports; never run a solver, fit a model or alter checkpoints."""
    onset = _read(figures / "g22_onset_resolution" / "summary.json")
    trajectory = _match(onset["protocols"], "cells", 256)
    if trajectory.get("exploratory_onset_time_r0p3") is None:
        raise ValueError("The saved G22 validation path has no threshold crossing")
    feedback = _read(figures / "g23_benchmark" / "summary.json")
    family = [row for row in feedback["rows"] if row["family"] == "field_0p25"]
    informed = _match(family, "control", "informed")
    blind = _match(family, "control", "blind")
    parity = _read(figures / "g24_linear_baseline" / "summary.json")
    parity_rank_two = _match(parity["ranks"], "rank", 2)
    shifted = _read(figures / "g24_scene_pair_linear" / "summary.json")
    shifted_full = _match(shifted["ranks"], "rank", 4)
    declared_map = _read(figures / "g24_scene_pair_linear" / "audit.json")["declared_target_map"]
    candidates = _read(figures / "g24_scene_pair" / "summary.json")
    attention = _match(candidates["candidates"], "candidate", "transformer")
    phase = _match(candidates["candidates"], "candidate", "phase_network")
    values = (
        ("gOnsetTime", _number(trajectory, "exploratory_onset_time_r0p3")),
        ("gOnsetCurrentCost", _number(trajectory, "exploratory_onset_cost_r0p3")),
        ("gOnsetCurrentFloor", _number(trajectory, "exploratory_onset_bound_r0p3")),
        ("gFeedbackInformedAccuracy", _number(informed, "heldout_accuracy")),
        ("gFeedbackBlindAccuracy", _number(blind, "heldout_accuracy")),
        ("gParityRankTwoFloor", _number(parity_rank_two, "predicted_train_floor")),
        ("gParityRankTwoHeldout", _number(parity_rank_two, "test_squared_error")),
        ("gSceneFullTrainError", _number(shifted_full, "train_squared_error")),
        ("gSceneFullHeldoutError", _number(shifted_full, "test_squared_error")),
        ("gSceneDeclaredMapHeldout", _number(declared_map, "test_squared_error")),
        ("gSceneAttentionHeldoutError", _number(attention, "test_squared_error")),
        ("gScenePhaseHeldoutError", _number(phase, "test_squared_error")),
    )
    lines = [
        "% Generated by simulations/g_followup_macros.py from saved JSON summaries.",
        "% Do not edit manually. Regeneration does not run a simulation or training sweep.",
        *(_macro(name, value) for name, value in values),
    ]
    return "\n".join(lines) + "\n"


def write() -> None:
    """Refresh only the TeX macro file from saved summaries."""
    OUTPUT.write_text(render(FIGURES))


if __name__ == "__main__":
    write()
