[project]
name = "simulations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "scipy>=1.17.1",
    "sympy>=1.14.0",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "mypy>=2.3.1",
    "radon>=6.0.1",
    "ruff>=0.16.5",
    "tach>=0.35.0",
    "vulture>=2.16",
    "xenon>=0.9.3",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "S"]
ignore = []

[tool.mypy]
strict = true
disallow_untyped_defs = true


[[tool.mypy.overrides]]
module = [
    "scipy.*",
    "tqdm.*",
    "sympy.*"
]
ignore_missing_imports = true
