"""Regenerate S6 figures and report from compact artifacts, without integration."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from structural_resonance import ROOT


def read_records(root: Path) -> list[dict[str, Any]]:
    return cast(list[dict[str, Any]], json.loads((root / "summary.json").read_text()))


def render_report(root: Path, output: Path) -> None:
    records = read_records(root)
    lines = [
        "# S6 joint phase/plasticity dynamics",
        "",
        "Generated by structural_resonance_report.py from summary.json; do not edit manually.",
        "",
        "Parameters and criteria: tasks/s6_execution.md. Each adaptive run has a frozen-K",
        "control with the same initial state and noise. Squared drift is a dissipation",
        "function, not entropy production. The cluster Gram template is diagnostic only.",
        "",
        "| Run | Tail r | Tail dissipation | Plateau change | "
        "True distance reduction | Shuffled reduction |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in records:
        lines.append(
            f"| {row['name']} | {row['tail_order']:.5f} | {row['tail_dissipation']:.3f} | "
            f"{row['plateau_relative_change']:.4f} | {row['true_distance_reduction']:.5f} | "
            f"{row['shuffled_distance_reduction']:.5f} |"
        )
    lines.extend(
        [
            "",
            f"Summed integration runtime: {sum(row['runtime_seconds'] for row in records):.2f} s.",
            "",
            "All adaptive runs maintain sampled r > 0.5 after t=10 and pass the declared",
            "5% plateau criterion. True-template distances increase and improve less than",
            "the shuffled control: this run does not exhibit structural resonance.",
            "Frozen controls have similar order and dissipation, so persistence of coherence",
            "alone is not evidence that plasticity improves the state. The positive objective",
            "contains a drive floor N*mean(omega)^2/D and fluctuating relative drift.",
            "A common drive cancels from the symmetric plasticity gradient.",
            "",
            "These finite seeded trajectories establish neither monotonic descent nor",
            "stationarity of the adaptive process, phase locking in the presence of noise,",
            "a thermodynamic entropy-production rate, or any E45/Lean obligation.",
            "No timestep or learning-rate convergence is inferred.",
        ]
    )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def plot(root: Path) -> None:
    records = read_records(root)
    fig, axes = plt.subplots(3, 1, figsize=(10, 10), sharex=True)
    for row in records:
        with np.load(root / f"{row['name']}.npz", allow_pickle=False) as data:
            time = data["time"]
            style = "-" if row["adaptive"] else "--"
            label = row["name"].replace("_", " ")
            window = 21
            axes[0].plot(
                np.convolve(time, np.ones(window) / window, "valid"),
                np.convolve(data["dissipation"], np.ones(window) / window, "valid"),
                style,
                alpha=0.7,
                label=label,
            )
            axes[1].plot(time, data["order"], style, alpha=0.6)
            if row["adaptive"]:
                (line,) = axes[2].plot(time, data["distance"], label=label + " true")
                axes[2].plot(
                    time,
                    data["shuffled_distance"],
                    ":",
                    color=line.get_color(),
                    label=label + " shuffled",
                )
    config = records[0]["config"]
    axes[1].axhline(1 / np.sqrt(config["n"]), color="black", ls=":", label=r"$1/\sqrt{N}$")
    axes[0].set_ylabel(r"Dissipation function $\sum_i v_i^2/D$")
    axes[1].set_ylabel("Order r")
    axes[2].set_ylabel("Frobenius distance")
    axes[2].set_xlabel("Time")
    for axis in axes:
        axis.grid(alpha=0.2)
        axis.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(root / "joint_dynamics.png", dpi=160)
    plt.close(fig)


def main() -> None:
    render_report(ROOT, ROOT / "REPORT.md")
    plot(ROOT)


if __name__ == "__main__":
    main()
