"""Regenerate S6 figures and report from compact artifacts, without integration."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from structural_resonance import ROOT

STYLES = {"gradient": "-", "random": "-.", "permuted": (0, (3, 1, 1, 1)), "frozen": "--"}


def read_records(root: Path, name: str = "summary.json") -> list[dict[str, Any]]:
    return cast(list[dict[str, Any]], json.loads((root / name).read_text()))


def table(records: list[dict[str, Any]]) -> list[str]:
    header = (
        "| Run | Tail r | Tail dissipation | Descent fraction | Plateau change | "
        "Norm growth | Within/between | Interleaved | Blind percentile | "
        "Permutation percentile |"
    )
    lines = [header, "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for row in records:
        lines.append(
            f"| {row['name']} | {row['tail_order']:.5f} | {row['tail_dissipation']:.3f} | "
            f"{row['descent_fraction']:.4f} | {row['plateau_relative_change']:.4f} | "
            f"{row['kernel_norm_growth']:.3f} | {row['tail_alignment_ratio']:.4f} | "
            f"{row['tail_crossed_alignment_ratio']:.4f} | "
            f"{row['blind_partition_percentile']:.4f} | "
            f"{row['permutation_percentile']:.4f} |"
        )
    return lines


def sweep_table(records: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| Learning rate | Tail dissipation | Min r after t=10 | Plateau change |",
        "|---:|---:|---:|---:|",
    ]
    for row in records:
        lines.append(
            f"| {row['learning_rate']:.3f} | {row['tail_dissipation']:.3f} | "
            f"{row['minimum_order_after_ten']:.4f} | {row['plateau_relative_change']:.4f} |"
        )
    return lines


def render_report(root: Path, output: Path) -> None:
    records = read_records(root)
    lines = [
        "# S6 joint phase/plasticity dynamics",
        "",
        "Generated by structural_resonance_report.py from summary.json and sweep.json;",
        "do not edit manually.",
        "",
        "Parameters and criteria: tasks/s6_execution.md. Each seed runs four arms on one",
        "phase-noise stream: a gradient step, a symmetric random step of the same Frobenius",
        "norm, that same gradient step under a random node relabelling, and a frozen",
        "kernel. Squared drift is a dissipation function, not entropy production. The",
        "cluster Gram template is diagnostic only.",
        "",
        "The descent fraction is the share of the frozen arm's headroom above the drive",
        "floor N*mean(omega)^2/D that an arm removes. The within/between ratio and the",
        "template correlation are invariant under rescaling the kernel; Frobenius distance",
        "to a template is not, and a fixed resource total does not hold the kernel norm",
        "fixed. The permutation percentile is the share of node relabellings whose",
        "template the final kernel sits closer to than it does to the true one. Kernel norm",
        "growth is the final over the initial Frobenius norm, and measures how far",
        "clip-and-rescale has concentrated the fixed resource onto fewer edges.",
        "",
        "Two partitions are scored on the same kernels. Within/between is the frequency",
        "partition, which is the structure the environment carries. Interleaved is a",
        "partition of the same group sizes balanced against it, carrying no frequency",
        "information. The blind percentile reads the frequency partition's ratio against",
        "the whole family of such partitions: it is the share of frequency-blind",
        "relabellings whose ratio is lower still, so a value near zero says the loss of",
        "within-cluster coupling belongs to the frequency partition rather than to block",
        "structure at large. Neither partition enters the update.",
        "",
        *table(records),
        "",
        f"Summed integration runtime: {sum(row['runtime_seconds'] for row in records):.2f} s.",
        "",
        "Learning-rate selection, one seed, gradient arm:",
        "",
        *sweep_table(read_records(root, "sweep.json")),
        "",
        "The production rate is the one at which the objective descends furthest while the",
        "run still meets the declared plateau criterion; larger rates lose descent without",
        "failing that criterion, so the sweep and not the criterion is what selects a rate.",
        "",
        "All gradient runs maintain sampled r > 0.5 after t=10 and pass the declared 5%",
        "plateau criterion. The objective descends well below the frozen arm; neither",
        "control arm does, so the descent and the loss of alignment are specific to the",
        "gradient rather than to motion of the kernel at fixed total resource.",
        "Within-cluster coupling falls relative to between-cluster coupling, and the final",
        "kernel is further from the true template than from nearly every node relabelling:",
        "this run does not exhibit structural resonance.",
        "",
        "Only the gradient arm's frequency partition is unusual against frequency-blind",
        "partitions of the same group sizes. Its interleaved ratio and those of the",
        "control arms sit inside the blind family, so the descent moves against the",
        "structure the environment carries rather than dissolving block structure of any",
        "kind: it is opposed to that structure, not indifferent to structure.",
        "",
        "The two controls separate two things that the matched-norm random arm alone",
        "confounds. Fresh isotropic steps cancel, so that arm ends far less deformed than",
        "the gradient arm and does not enter the sparsification channel that",
        "clip-and-rescale opens. The permuted arm takes the gradient step itself under a",
        "random node relabelling: a relabelling is an isometry that leaves the multiset of",
        "step entries alone, so the arm deforms the kernel as the gradient arm does and",
        "differs from it only in which edges the step reaches. Its kernel norm growth,",
        "within/between ratio and permutation percentile are the columns to read against",
        "the gradient arm's.",
        "",
        "Minimizing squared drift under a conserved mean drift equalizes drift across",
        "nodes, which rewards coupling between clusters of unlike frequency. The template",
        "rewards coupling within clusters of like frequency. That the objective's optimum",
        "and the template disagree is a property of this pairing, not a general result",
        "about dissipation.",
        "",
        "These finite seeded trajectories establish neither monotonic descent nor",
        "stationarity of the adaptive process, phase locking in the presence of noise,",
        "a thermodynamic entropy-production rate, or any E45/Lean obligation.",
        "No timestep convergence is inferred, and the learning rate is selected by the",
        "sweep above rather than by a convergence argument.",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _panels(axes: list[Any], root: Path, row: dict[str, Any]) -> None:
    with np.load(root / f"{row['name']}.npz", allow_pickle=False) as data:
        time, style = data["time"], STYLES[row["mode"]]
        label = row["name"].replace("_", " ")
        window = 21
        axes[0].plot(
            np.convolve(time, np.ones(window) / window, "valid"),
            np.convolve(data["dissipation"], np.ones(window) / window, "valid"),
            linestyle=style,
            alpha=0.7,
            label=label,
        )
        axes[1].plot(time, data["order"], linestyle=style, alpha=0.6)
        axes[2].plot(time, data["alignment_ratio"], linestyle=style, alpha=0.7)
        if row["mode"] != "frozen":
            (line,) = axes[3].plot(
                time, data["distance"], linestyle=style, alpha=0.7, label=label + " true"
            )
            axes[3].plot(time, data["shuffled_distance"], ":", color=line.get_color(), alpha=0.7)


def plot(root: Path) -> None:
    records = read_records(root)
    fig, axes = plt.subplots(4, 1, figsize=(8, 11), sharex=True)
    for row in records:
        _panels(list(axes), root, row)
    config = records[0]["config"]
    axes[0].axhline(records[0]["sigma_floor"], color="black", ls=":", label=r"drive floor")
    axes[1].axhline(1 / np.sqrt(config["n"]), color="black", ls=":", label=r"$1/\sqrt{N}$")
    axes[2].axhline(1.0, color="black", ls=":", label="no cluster preference")
    axes[3].plot([], [], ":", color="black", label="node-label shuffle")
    axes[0].set_ylabel(r"Dissipation function $\sum_i v_i^2/D$")
    axes[1].set_ylabel("Order r")
    axes[2].set_ylabel("Within/between coupling")
    axes[3].set_ylabel("Frobenius distance")
    axes[3].set_xlabel("Time")
    for axis in axes:
        axis.grid(alpha=0.2)
        axis.legend(fontsize=8, ncol=2)
    fig.tight_layout()
    fig.savefig(root / "joint_dynamics.png", dpi=160)
    plt.close(fig)


def main() -> None:
    render_report(ROOT, ROOT / "REPORT.md")
    plot(ROOT)


if __name__ == "__main__":
    main()
