import re
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import cast

from repo_root import REPO
from simulation_tex import (
    _effective_coupling,
    _first_sustained_index,
    _geometric_grid_ratio,
    _largest_usable_bin_count,
    _scientific_upper_bound,
    _shared_coherent_length,
    generate_simulation_tex,
)


class SimulationTexTest(unittest.TestCase):
    def test_generator_reads_saved_outputs_without_running_integrators(self) -> None:
        with TemporaryDirectory() as directory:
            output = Path(directory) / "simulation_results.tex"
            generate_simulation_tex(output)
            content = output.read_text(encoding="utf-8")

        self.assertIn("Auto-generated by simulations/simulation_tex.py", content)
        self.assertIn(r"\newcommand{\rampDelayExponent}{0.443}", content)
        self.assertIn(r"\newcommand{\spatialCriticalDecay}{0.0140}", content)
        self.assertIn(r"\newcommand{\waveBoundary}{0.1871}", content)
        self.assertIn(r"\newcommand{\waveRetainedMax}{0.1750}", content)
        self.assertIn(r"\newcommand{\waveLostMin}{0.2000}", content)
        self.assertIn(r"\newcommand{\waveBandOrder}{0.0083}", content)
        self.assertIn(r"\newcommand{\waveBandControlOrder}{0.9657}", content)
        self.assertIn(r"\newcommand{\waveControlGapMax}{0.0001}", content)
        self.assertIn(r"\newcommand{\waveSpreadBoundary}{0.1421}", content)
        self.assertIn(r"\newcommand{\waveSpreadBandOrder}{0.0348}", content)
        self.assertIn(r"\newcommand{\waveSpreadBandControlOrder}{0.9418}", content)
        self.assertIn(r"\newcommand{\waveSeedRetained}{9}", content)
        self.assertIn(r"\newcommand{\waveSeedTotal}{9}", content)
        self.assertIn(r"\newcommand{\selectionRateSlope}{0.41505}", content)
        self.assertIn(r"\newcommand{\chaosBesselResidual}{0.00191}", content)
        self.assertIn(r"\newcommand{\frustrationCouplingMin}", content)
        self.assertIn(r"\newcommand{\plasticityOrderMin}{0.9167}", content)
        self.assertIn(r"\newcommand{\plasticityStudyCaseCount}{6}", content)
        self.assertIn(r"\newcommand{\plasticityStudyEligibleCount}{0}", content)
        self.assertIn(r"\newcommand{\plasticityStudyProductionPostUpdate}{1118.95}", content)
        self.assertIn(r"\newcommand{\plasticityStudyProductionInterval}{1383.87}", content)
        self.assertIn(r"\newcommand{\plasticityStudyProductionFrozen}{1383.06}", content)
        self.assertIn(r"\newcommand{\plasticityStudyProductionRatioMin}{0.998}", content)
        self.assertIn(r"\newcommand{\plasticityStudyProductionRatioMax}{1.003}", content)
        self.assertIn(r"\newcommand{\recoveryStudyCaseCount}{18}", content)
        self.assertIn(r"\newcommand{\recoveryStudyUniqueCount}{0}", content)
        self.assertIn(r"\newcommand{\recoveryStudyFitSpread}{8.9\times10^{-16}}", content)
        self.assertIn(r"\newcommand{\recoveryStudyMaxSquaredError}{5.2\times10^{-14}}", content)
        self.assertIn(r"\newcommand{\plasticityDescentMin}{0.6773}", content)
        self.assertIn(r"\newcommand{\plasticityRandomDescentMax}{-0.0103}", content)
        self.assertIn(r"\newcommand{\collapseLinearDeviation}{0.0095}", content)
        self.assertIn(r"\newcommand{\collapseTanhDeviation}{0.0030}", content)
        self.assertIn(r"\newcommand{\collapseProbeSeparation}{0.154}", content)
        self.assertIn(r"\newcommand{\collapseTargetConcentration}{1.56}", content)
        self.assertIn(r"\newcommand{\eegCrossSubjectCount}{8}", content)
        self.assertIn(r"\newcommand{\eegCalibrationSmallSamples}{100}", content)
        self.assertIn(r"\newcommand{\frustrationBracketMin}{1.958}", content)
        self.assertIn(r"\newcommand{\frustrationCoarseMin}{1.857}", content)
        self.assertIn(r"\newcommand{\frustrationRefinementStep}{0.025}", content)
        self.assertIn(r"\newcommand{\frustrationGridRatio}{1.136}", content)
        self.assertIn(r"\newcommand{\rampOnsetPinnedCount}{4}", content)
        self.assertIn(r"\newcommand{\rampLegCount}{4}", content)
        self.assertIn(r"\newcommand{\spatialCriticalDecayCells}{0.90}", content)
        self.assertIn(r"\newcommand{\spatialResolvedDecayCells}{0.94}", content)
        self.assertIn(r"\newcommand{\spatialRefinedCriticalDecayCells}{1.81}", content)
        self.assertIn(r"\newcommand{\spatialRefinedBoundaryRatio}{1.01}", content)
        self.assertIn(r"\newcommand{\spatialPlateauExtentRatio}{4.0}", content)
        self.assertIn(r"\newcommand{\spatialSharedCoherentDecay}{0.01467}", content)
        self.assertIn(r"\newcommand{\spatialSharedCoarseOrder}{0.6176}", content)
        self.assertIn(r"\newcommand{\spatialSharedRefinedOrder}{0.2687}", content)
        self.assertIn(r"\newcommand{\designUsableBins}{24}", content)
        self.assertIn(r"\newcommand{\designSitesIndependent}{3000}", content)
        self.assertIn(r"\newcommand{\designSitesClustered}{31000}", content)
        self.assertIn(r"\newcommand{\reductionRuleSpread}{0.003}", content)
        self.assertIn(r"\newcommand{\reductionMeanFieldRatio}{0.750}", content)
        self.assertIn(r"\newcommand{\reductionHeterogeneousRatio}{1.53}", content)
        self.assertIn(r"\newcommand{\overlapIncompatibleAuc}{0.990}", content)
        self.assertIn(r"\newcommand{\overlapShrinkageStatistic}{0.0146}", content)
        self.assertIn(r"\newcommand{\overlapPhaseShareBuilt}{1.000}", content)
        self.assertIn(r"\newcommand{\quasistaticExponentAll}{0.447}", content)
        self.assertIn(r"\newcommand{\quasistaticExponentUncensored}{0.418}", content)
        self.assertIn(r"\newcommand{\quasistaticCrossingResidualMin}{0.393}", content)
        self.assertIn(r"\newcommand{\quasistaticCrossingResidualMax}{0.393}", content)
        self.assertIn(r"\newcommand{\noiseFastMeanGap}{0.035}", content)
        self.assertIn(r"\newcommand{\noiseSlowQuasiGap}{0.020}", content)
        self.assertIn(r"\newcommand{\noiseRefusals}{25}", content)
        self.assertNotIn(r"\rampOnsetPinnedOne", content)
        # A macro nobody cites is a dead entry in this file and in its drift test.
        # Scoped to the five groups read from the N7-N13 summaries: the older
        # groups carry uncited entries of their own, and deciding each one's fate
        # is a separate pass from the one that added these.
        published = REPO
        prose = (published / "main.tex").read_text(encoding="utf-8") + (
            published / "supplementary.tex"
        ).read_text(encoding="utf-8")
        groups = ("design", "reduction", "overlap", "quasistatic", "noise")
        emitted = re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", content)
        uncited = [name for name in emitted if name.startswith(groups) and f"\\{name}" not in prose]
        self.assertEqual(uncited, [], f"generated but never cited: {uncited}")

    def test_committed_macros_match_saved_results(self) -> None:
        with TemporaryDirectory() as directory:
            regenerated = Path(directory) / "simulation_results.tex"
            generate_simulation_tex(regenerated)
            expected = regenerated.read_text(encoding="utf-8")

        committed = Path(__file__).with_name("simulation_results.tex").read_text(encoding="utf-8")
        self.assertEqual(committed, expected)


class DerivedQuantityTest(unittest.TestCase):
    def test_effective_coupling_uses_the_run_own_size_and_diffusion(self) -> None:
        self.assertAlmostEqual(_effective_coupling(0.008, {"n": 250, "diffusion": 2.0}), 1.0)

    def test_grid_ratio_reads_the_grid_rather_than_the_bracket(self) -> None:
        self.assertAlmostEqual(_geometric_grid_ratio([0.0, 1.0, 2.0, 4.0, 8.0]), 2.0)

    def test_first_sustained_index_ignores_an_earlier_isolated_crossing(self) -> None:
        self.assertEqual(_first_sustained_index([0.05, 0.30, 0.10, 0.40, 0.90], 0.2), 3)

    def test_shared_length_is_the_later_of_the_two_coherent_onsets(self) -> None:
        # The coarse sheet is sustained-coherent from 2.0 and the refined one
        # only from 3.0, so 3.0 is where a steady order both call coherent sits.
        self.assertAlmostEqual(
            _shared_coherent_length(
                [1.0, 2.0, 3.0], [0.1, 0.9, 0.9], [1.0, 2.0, 3.0], [0.1, 0.1, 0.9]
            ),
            3.0,
        )

    def test_shared_length_rejects_an_onset_the_other_sheet_never_samples(self) -> None:
        with self.assertRaises(ValueError):
            _shared_coherent_length([1.0, 2.0], [0.1, 0.9], [1.0, 4.0], [0.1, 0.9])

    def test_largest_usable_bin_count_reads_the_coarsest_passing_design(self) -> None:
        rows: list[dict[str, object]] = [
            {"bins": 6, "dependence": 0.0, "a_min": 1.5},
            {"bins": 24, "dependence": 0.0, "a_min": 1.5},
            {"bins": 40, "dependence": 0.0, "a_min": None},
            {"bins": 40, "dependence": 1.0, "a_min": 2.0},
        ]
        self.assertEqual(_largest_usable_bin_count(rows, 0.0), (24, 1.5))

    def test_largest_usable_bin_count_rejects_a_dependence_nothing_clears(self) -> None:
        with self.assertRaises(ValueError):
            _largest_usable_bin_count(
                [cast(dict[str, object], {"bins": 40, "dependence": 0.0, "a_min": None})], 0.0
            )

    def test_scientific_bound_rounds_away_from_the_value_it_bounds(self) -> None:
        # The publication states these as "at most", so truncation would overclaim.
        self.assertEqual(_scientific_upper_bound(8.881784197001252e-16), r"8.9\times10^{-16}")
        self.assertEqual(_scientific_upper_bound(5.1944999412767196e-14), r"5.2\times10^{-14}")
        self.assertEqual(_scientific_upper_bound(1.001e-3), r"1.1\times10^{-3}")
        self.assertEqual(_scientific_upper_bound(0.0), r"0")


if __name__ == "__main__":
    unittest.main()
