import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from simulation_tex import generate_simulation_tex


class SimulationTexTest(unittest.TestCase):
    def test_generator_reads_saved_outputs_without_running_integrators(self) -> None:
        with TemporaryDirectory() as directory:
            output = Path(directory) / "simulation_results.tex"
            generate_simulation_tex(output)
            content = output.read_text(encoding="utf-8")

        self.assertIn("Auto-generated by simulations/simulation_tex.py", content)
        self.assertIn(r"\newcommand{\rampDelayExponent}{0.443}", content)
        self.assertIn(r"\newcommand{\spatialCriticalDecay}{0.0140}", content)
        self.assertIn(r"\newcommand{\selectionRateSlope}{0.43240}", content)
        self.assertIn(r"\newcommand{\chaosBesselResidual}{0.00191}", content)
        self.assertIn(r"\newcommand{\frustrationCouplingMin}", content)
        self.assertIn(r"\newcommand{\plasticityOrderMin}{0.9167}", content)
        self.assertIn(r"\newcommand{\plasticityDescentMin}{0.6773}", content)
        self.assertIn(r"\newcommand{\plasticityRandomDescentMax}{-0.0103}", content)

    def test_committed_macros_match_saved_results(self) -> None:
        with TemporaryDirectory() as directory:
            regenerated = Path(directory) / "simulation_results.tex"
            generate_simulation_tex(regenerated)
            expected = regenerated.read_text(encoding="utf-8")

        committed = Path(__file__).with_name("simulation_results.tex").read_text(encoding="utf-8")
        self.assertEqual(committed, expected)


if __name__ == "__main__":
    unittest.main()
