"""Generate the physical-unity paper's numerals from the saved U3 summaries only.

Reads ``figures/unity_agreement/summary.json`` (the sheet simulations) and
``resistance.json`` (the exact resistance scaling) and writes
``unity/unity_results.tex``. Nothing here integrates a sheet or sums a Fourier
series: ``unity_agreement.py`` produces both summaries as a separate command.
"""

import json
import math
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parent
FIGURES = ROOT / "figures"
OUTPUT = ROOT.parent / "unity" / "unity_results.tex"

# TeX macro names cannot hold digits, so shapes are spelled out.
SHAPE_NAMES = {
    "nearest": "Nearest",
    "exponential": "Exponential",
    "power_sigma1": "SigmaOne",
    "power_sigma3": "SigmaThree",
}


def _read(path: Path) -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(path.read_text()))


def _finite(value: object) -> float:
    number = float(cast(float, value))
    if not math.isfinite(number):
        raise ValueError(f"Nonfinite saved result: {value}")
    return number


def _select(runs: list[dict[str, Any]], **config: float) -> list[dict[str, Any]]:
    found = [r for r in runs if all(r["config"][k] == v for k, v in config.items())]
    if not found:
        raise ValueError(f"No saved run with {config}")
    return found


def _ordered_values(runs: list[dict[str, Any]], high: float) -> list[tuple[str, str]]:
    ordered = [r for r in runs if float(r["config"]["noise"]) < high]
    logarithmic = [r for r in ordered if r["fit"]["better"] == "logarithmic"]
    return [("uOrderedRuns", str(len(ordered))), ("uLogarithmicRuns", str(len(logarithmic)))]


def _harmonic_values(runs: list[dict[str, Any]], low: float, mid: float) -> list[tuple[str, str]]:
    values = []
    for name, noise in (("Low", low), ("Mid", mid)):
        ratio = max(_finite(r["harmonic_ratio_max"]) for r in _select(runs, noise=noise))
        values.append((f"uHarmonicRatio{name}", f"{ratio:.2f}"))
    return values


def _chord_values(runs: list[dict[str, Any]], high: float, side: int) -> list[tuple[str, str]]:
    disordering = _select(runs, noise=high, side=side)
    values = []
    for shape, name in SHAPE_NAMES.items():
        (run,) = [r for r in disordering if r["shape"] == shape]
        values.append((f"uChord{name}High", f"{_finite(run['discrepancy'][-1]):.2f}"))
    return values


def _simulation_values(summary: dict[str, Any]) -> list[tuple[str, str]]:
    runs = cast(list[dict[str, Any]], summary["runs"])
    if not runs:
        raise ValueError("The saved U3 summary has no runs")
    low, mid, high = sorted({float(r["config"]["noise"]) for r in runs})
    sides = sorted({int(r["config"]["side"]) for r in runs})
    return [
        ("uNoiseLow", f"{low:g}"),
        ("uNoiseMid", f"{mid:g}"),
        ("uNoiseHigh", f"{high:g}"),
        ("uSideSmall", str(sides[0])),
        ("uSideLarge", str(sides[-1])),
        *_ordered_values(runs, high),
        *_harmonic_values(runs, low, mid),
        *_chord_values(runs, high, sides[-1]),
    ]


def _scaling_values(scaling: dict[str, Any]) -> list[tuple[str, str]]:
    sides = [int(side) for side in scaling["sides"]]
    values = [(f"uScalingSide{label}", str(side)) for label, side in zip("ABC", sides, strict=True)]
    for shape in ("exponential", "power_sigma1", "power_sigma3"):
        far = scaling["far_resistance"][shape]
        for label, resistance in zip("ABC", far, strict=True):
            values.append((f"uFar{SHAPE_NAMES[shape]}{label}", f"{_finite(resistance):.3f}"))
    stiffness = scaling["stiffness"]
    ratio = _finite(stiffness["exponential"]) / _finite(stiffness["nearest"])
    values.append(("uStiffnessRatio", f"{ratio:.0f}"))
    return values


def render(figures: Path) -> str:
    """Read saved summaries; never integrate a sheet or recompute a resistance."""
    directory = figures / "unity_agreement"
    values = _simulation_values(_read(directory / "summary.json"))
    values += _scaling_values(_read(directory / "resistance.json"))
    lines = [
        "% Generated by simulations/unity_macros.py from saved JSON summaries in",
        "% simulations/figures/unity_agreement/. Do not edit manually.",
        "% Regeneration does not run a simulation.",
        *(f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in values),
    ]
    return "\n".join(lines) + "\n"


def write() -> None:
    """Refresh only the TeX macro file from saved summaries."""
    OUTPUT.write_text(render(FIGURES))


if __name__ == "__main__":
    write()
