/-
  Phase 3: Principle of Least Action and Structural Resonance
  
  This module formalizes:
  1. Trajectories and Thermodynamic Action
  2. The ELBO (Evidence Lower Bound) Decomposition
  3. The Principle of Least Action
  4. Structural Resonance as the minimal action state
-/

import PhysicsOfConsciousness.Phase2_Thermodynamics
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

namespace PhysicsOfConsciousness

open Finset

-- We require a Thermodynamic system
variable {sys : Type} [FinitePhaseSpace sys] [Thermodynamics sys]

-- The space of possible trajectories for our dissipative structure.
structure Trajectory (sys : Type) where
  path : Real → (sys → sys) -- time to state transitions

-- A generative statistical model mapping internal states to environmental states
class GenerativeModel (sys : Type) (env : Type) where
  joint_prob : sys → env → Real
  marginal_env : env → Real
  conditional_prob : sys → env → Real
  bayes_rule : ∀ x e, joint_prob x e = conditional_prob x e * marginal_env e
  cond_prob_pos : ∀ x e, conditional_prob x e > 0
  marg_env_pos : ∀ e, marginal_env e > 0

class StatisticalSystem (sys : Type) [FinitePhaseSpace sys] where
  -- The statistical distribution of internal state transitions generated by a trajectory
  generative_model : Trajectory sys → (sys → Real)
  prob_pos : ∀ traj x, generative_model traj x > 0
  sum_to_one : ∀ traj, ∑ x, generative_model traj x = 1

-- Formalize KL divergence
noncomputable def kl_divergence {α : Type} [Fintype α] (P Q : α → Real) : Real :=
  ∑ x : α, P x * Real.log (P x / Q x)

axiom gibbs_inequality {α : Type} [Fintype α] (P Q : α → Real) : kl_divergence P Q ≥ 0

axiom kl_divergence_zero_implies_identical {α : Type} [Fintype α] (P Q : α → Real) :
  kl_divergence P Q = 0 → ∀ x, P x = Q x

noncomputable def mismatch {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] 
  (traj : Trajectory sys) (e : env) : Real :=
  kl_divergence (StatisticalSystem.generative_model (sys := sys) traj) (fun x => GenerativeModel.conditional_prob (sys := sys) x e)

-- Surprise is the negative log marginal probability of the environment
noncomputable def surprise {env : Type} {sys : Type} [GenerativeModel sys env] (e : env) : Real :=
  - Real.log (GenerativeModel.marginal_env (sys := sys) e)

-- Variational Free Energy (VFE)
noncomputable def variational_free_energy {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] 
  (traj : Trajectory sys) (e : env) : Real :=
  ∑ x : sys, (StatisticalSystem.generative_model (sys := sys) traj x) * 
    Real.log ((StatisticalSystem.generative_model (sys := sys) traj x) / GenerativeModel.joint_prob (sys := sys) x e)

-- The ELBO Decomposition Theorem: VFE mathematically decomposes into Surprise + Mismatch (KL Divergence).
-- This replaces the tautological `action_is_vfe` axiom from the previous iteration.
theorem elbo_decomposition {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] 
  (traj : Trajectory sys) (e : env) :
  variational_free_energy (sys := sys) traj e = surprise (sys := sys) e + mismatch (sys := sys) (env := env) traj e := by
  dsimp [variational_free_energy, surprise, mismatch, kl_divergence]
  have h1 : ∀ x, Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = 
    Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.conditional_prob (sys := sys) x e) + Real.log (GenerativeModel.marginal_env (sys := sys) e)⁻¹ := by
    intro x
    rw [GenerativeModel.bayes_rule (sys := sys) x e]
    have h_div : StatisticalSystem.generative_model (sys := sys) traj x / (GenerativeModel.conditional_prob (sys := sys) x e * GenerativeModel.marginal_env (sys := sys) e) = 
      (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.conditional_prob (sys := sys) x e) * (GenerativeModel.marginal_env (sys := sys) e)⁻¹ := by ring
    rw [h_div]
    apply Real.log_mul
    · have hP : StatisticalSystem.generative_model (sys := sys) traj x > 0 := StatisticalSystem.prob_pos (sys := sys) traj x
      have hQ : GenerativeModel.conditional_prob (sys := sys) x e > 0 := GenerativeModel.cond_prob_pos (sys := sys) x e
      exact div_pos hP hQ |>.ne'
    · have hQm : GenerativeModel.marginal_env (sys := sys) e > 0 := GenerativeModel.marg_env_pos (sys := sys) e
      exact inv_pos.mpr hQm |>.ne'
  
  have h2 : ∑ x, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = 
    ∑ x, StatisticalSystem.generative_model (sys := sys) traj x * (Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.conditional_prob (sys := sys) x e) - Real.log (GenerativeModel.marginal_env (sys := sys) e)) := by
    apply sum_congr rfl
    intro x _
    rw [h1 x]
    rw [Real.log_inv]
    ring
    
  rw [h2]
  have h3 : ∑ x, StatisticalSystem.generative_model (sys := sys) traj x * (Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.conditional_prob (sys := sys) x e) - Real.log (GenerativeModel.marginal_env (sys := sys) e)) = 
    ∑ x, (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.conditional_prob (sys := sys) x e) - StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.marginal_env (sys := sys) e)) := by
    apply sum_congr rfl
    intro x _
    ring
  rw [h3]
  rw [sum_sub_distrib]
  have h4 : ∑ x, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.marginal_env (sys := sys) e) = 
    (∑ x, StatisticalSystem.generative_model (sys := sys) traj x) * Real.log (GenerativeModel.marginal_env (sys := sys) e) := by
    rw [← sum_mul]
  rw [h4, StatisticalSystem.sum_to_one (sys := sys) traj]
  ring

-- Thermodynamic state variables mapping to the environment
class ThermodynamicSystem (sys env : Type) [FinitePhaseSpace sys] [GenerativeModel sys env] extends Thermodynamics sys where
  -- The physical energy of a state x in environment e is given by the Boltzmann distribution mapping
  energy : sys → env → Real
  boltzmann_dist : ∀ x e, GenerativeModel.joint_prob (sys := sys) x e = Real.exp (-(energy x e) / temperature)

-- The expected internal energy of the system given a trajectory
noncomputable def expected_energy {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] [ThermodynamicSystem sys env] (traj : Trajectory sys) (e : env) : Real :=
  ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * ThermodynamicSystem.energy x e

-- The Shannon entropy of the system's distribution
noncomputable def shannon_entropy {sys : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] (traj : Trajectory sys) : Real :=
  - ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x)

-- Thermodynamic Free Energy = U - TS
noncomputable def thermodynamic_free_energy {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] [ThermodynamicSystem sys env] (traj : Trajectory sys) (e : env) : Real :=
  expected_energy (sys := sys) (env := env) traj e - Thermodynamics.temperature (sys := sys) * shannon_entropy (sys := sys) traj

-- Proof that Thermodynamic Free Energy is exactly proportional to Variational Free Energy
theorem free_energy_is_vfe {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] [ThermodynamicSystem sys env] (traj : Trajectory sys) (e : env) :
  thermodynamic_free_energy (sys := sys) traj e = Thermodynamics.temperature (sys := sys) * variational_free_energy (sys := sys) traj e := by
  dsimp [thermodynamic_free_energy, expected_energy, shannon_entropy, variational_free_energy]
  have h1 : ∀ x, ThermodynamicSystem.energy x e = - Thermodynamics.temperature (sys := sys) * Real.log (GenerativeModel.joint_prob (sys := sys) x e) := by
    intro x
    have h_boltz := ThermodynamicSystem.boltzmann_dist x e
    have h_log : Real.log (GenerativeModel.joint_prob (sys := sys) x e) = -(ThermodynamicSystem.energy x e) / Thermodynamics.temperature (sys := sys) := by 
      rw [h_boltz, Real.log_exp]
    have h_mul : Real.log (GenerativeModel.joint_prob (sys := sys) x e) * Thermodynamics.temperature (sys := sys) = -(ThermodynamicSystem.energy x e) := by
      rw [h_log]
      have hT : Thermodynamics.temperature (sys := sys) ≠ 0 := ne_of_gt Thermodynamics.temperature_pos
      exact div_mul_cancel₀ _ hT
    linarith

  have h2 : ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * ThermodynamicSystem.energy x e = 
    ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * (- Thermodynamics.temperature (sys := sys) * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
    apply sum_congr rfl
    intro x _
    rw [h1 x]

  have h3 : ∀ x, StatisticalSystem.generative_model (sys := sys) traj x * (- Thermodynamics.temperature (sys := sys) * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) = 
    - Thermodynamics.temperature (sys := sys) * (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
    intro x
    ring
    
  have h4 : ∑ x : sys, - Thermodynamics.temperature (sys := sys) * (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) = 
    - Thermodynamics.temperature (sys := sys) * ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e) := by
    rw [← mul_sum]
    
  have h5 : ∀ x, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = 
    StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x) - StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e) := by
    intro x
    have h_div : Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = Real.log (StatisticalSystem.generative_model (sys := sys) traj x) - Real.log (GenerativeModel.joint_prob (sys := sys) x e) := by
      apply Real.log_div
      · exact StatisticalSystem.prob_pos (sys := sys) traj x |>.ne'
      · have hb := ThermodynamicSystem.boltzmann_dist x e
        rw [hb]
        exact Real.exp_pos _ |>.ne'
    rw [h_div]
    ring
    
  have h6 : ∑ x : sys, (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x) - StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) = 
    (∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x)) - (∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
    rw [sum_sub_distrib]
    
  have h3_sum : ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * (- Thermodynamics.temperature (sys := sys) * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) = 
    ∑ x : sys, - Thermodynamics.temperature (sys := sys) * (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
    apply sum_congr rfl
    intro x _
    exact h3 x
  rw [h2, h3_sum, h4]
  have h_rhs_sum : ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = 
    (∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x)) - (∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
    have hs : ∑ x : sys, StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x / GenerativeModel.joint_prob (sys := sys) x e) = ∑ x : sys, (StatisticalSystem.generative_model (sys := sys) traj x * Real.log (StatisticalSystem.generative_model (sys := sys) traj x) - StatisticalSystem.generative_model (sys := sys) traj x * Real.log (GenerativeModel.joint_prob (sys := sys) x e)) := by
      apply sum_congr rfl
      intro x _
      exact h5 x
    rw [hs]
    exact h6
    
  rw [h_rhs_sum]
  ring

-- We abstract the Action functional via a class.
class ActionSystem (sys : Type) (env : Type) where
  action : Trajectory sys → env → Real

def Action {sys env : Type} [ActionSystem sys env] (traj : Trajectory sys) (e : env) : Real :=
  ActionSystem.action traj e

-- The ActiveInferenceSystem now rigorously defines its action as the temperature-scaled thermodynamic free energy.
class ActiveInferenceSystem (sys : Type) (env : Type) [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] extends ThermodynamicSystem sys env, ActionSystem sys env where
  action_def : ∀ (traj : Trajectory sys) (e : env), 
    Action traj e = thermodynamic_free_energy (sys := sys) traj e / Thermodynamics.temperature (sys := sys)

-- Theorem: Thermodynamic Action equates to Variational Free Energy.
-- This was previously an axiom (`action_is_vfe`). Now it is a derived consequence of stat-mech.
theorem action_is_vfe {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] [ActiveInferenceSystem sys env] (traj : Trajectory sys) (e : env) :
  Action traj e = variational_free_energy (sys := sys) traj e := by
  rw [ActiveInferenceSystem.action_def]
  have h_fe := free_energy_is_vfe (sys := sys) (env := env) traj e
  rw [h_fe]
  have hT : Thermodynamics.temperature (sys := sys) ≠ 0 := ne_of_gt (Thermodynamics.temperature_pos)
  exact mul_div_cancel_left₀ (variational_free_energy (sys := sys) traj e) hT

-- Principle of Least Action: The physically realized trajectory minimizes the action.
def is_physically_realized {sys env : Type} [ActionSystem sys env] (traj : Trajectory sys) (e : env) : Prop :=
  ∀ other : Trajectory sys, Action traj e ≤ Action other e

-- Structural Resonance: The system minimizes its mismatch (KL divergence) with the environment globally.
def achieves_structural_resonance {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] 
  (traj : Trajectory sys) (e : env) : Prop :=
  ∀ other : Trajectory sys, mismatch (sys := sys) (env := env) traj e ≤ mismatch (sys := sys) (env := env) other e

-- Core Theorem: The Resonance Inevitability
-- The action is minimized if and only if the system achieves structural resonance with the environment.
-- This is now derived via the mathematical ELBO decomposition and Stat-Mech Action derivations.
theorem resonance_minimizes_action {sys env : Type} [FinitePhaseSpace sys] [StatisticalSystem sys] [GenerativeModel sys env] [ActiveInferenceSystem sys env]
  (traj : Trajectory sys) (e : env) :
  is_physically_realized traj e ↔ achieves_structural_resonance traj e := by
  dsimp [is_physically_realized, achieves_structural_resonance]
  constructor
  · intro h other
    have h1 := h other
    -- Apply the derived identity to convert Action to VFE
    rw [action_is_vfe traj e, action_is_vfe other e] at h1
    -- Apply the mathematical ELBO decomposition theorem
    rw [elbo_decomposition traj e, elbo_decomposition other e] at h1
    -- The surprise term cancels out, leaving mismatch
    linarith
  · intro h other
    have h1 := h other
    rw [action_is_vfe traj e, action_is_vfe other e]
    rw [elbo_decomposition traj e, elbo_decomposition other e]
    linarith

-- Topological Protection vs. Dissolution
class TopologicalSystem (sys : Type) extends ActionSystem sys Unit where
  charge : (sys → sys) → Int

axiom topological_protection {sys : Type} [TopologicalSystem sys] :
  ∀ (traj : Trajectory sys), (∃ t, TopologicalSystem.charge (traj.path t) ≠ 0) → (∀ t, TopologicalSystem.charge (traj.path t) ≠ 0)

end PhysicsOfConsciousness
